CorpAnalytica_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      dbname: dev
      host: de-4-3-redshift.862327261051.us-west-2.redshift-serverless.amazonaws.com
      password: "{{ env_var('dbt_password') }}"
      port: 5439
      schema: analytics
      threads: 1
      user: "{{ env_var('dbt_user') }}"

