# Generated by Django 4.2 on 2023-08-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpanalytica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('corpname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
    ]
