# Generated by Django 4.2 on 2023-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpanalytica', '0002_test_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='corp_detail',
            fields=[
                ('crno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('corpnm', models.CharField(max_length=100)),
                ('enppbancmpynm', models.CharField(max_length=100)),
                ('enprprfnm', models.CharField(max_length=20)),
                ('corpregmrktdcdnm', models.CharField(max_length=50)),
                ('bzno', models.CharField(max_length=15)),
                ('enpbsadr', models.CharField(max_length=300)),
                ('enpdtadr', models.CharField(max_length=100)),
                ('enphmpgurl', models.CharField(max_length=200)),
                ('enptlno', models.CharField(max_length=30)),
                ('smenpyn', models.CharField(max_length=30)),
                ('enpmainbiznm', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'corp_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='corp_keyword',
            fields=[
                ('corpname', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'corp_keyword',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='corp_basic',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='test_table',
            options={'managed': False},
        ),
    ]
