# Generated by Django 4.0 on 2023-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpanalytica', '0003_corp_detail_corp_keyword_alter_corp_basic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='naver_news',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('corpname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'naver_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='news_article',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('corpname', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'news_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='news_keyword',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('corpname', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'news_keyword',
                'managed': False,
            },
        ),
    ]
