# Generated by Django 4.0 on 2023-08-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpanalytica', '0004_naver_news_news_article_news_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='corp_total_info',
            fields=[
                ('crno', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('entno', models.CharField(max_length=8)),
                ('corpname', models.CharField(max_length=256)),
                ('public_corpname', models.CharField(max_length=256)),
                ('owner', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=513)),
                ('homepage_url', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('keyword', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corp_total_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test_table',
        ),
    ]
